[package]
name = "monie-rpc"
version = "0.1.0"
authors = ["nie <nie@usmonie.com>"]
edition = "2021"

[dependencies]
tonic = { version = "0.9.1", features = ["transport", "gzip"] }
prost = "0.11.3"
prost-types = "0.11.2"

[build-dependencies]
tonic-build = "0.9.1"